### ISSUE TITLE
artifacts in waterfall

### ISSUE THREAD

**Issue by jonschoning** [adamwalker/sdr-apps#1]
Might just be because waterfall is a test app, but noticed some artifacts in the output, perhaps when the intensity of the received signals change?

![waterfall-sdr-artifacts](https://cloud.githubusercontent.com/assets/137183/7993482/f91a5228-0acb-11e5-9693-4e95a461fa58.png)

**Comment by adamwalker** [comment]
You mean the big block about half way down that's a bit darker?

I get those too. I had assumed they were because the chip changed its gain or something. 

If its caused by the hardware then theres not much that can be done about it. Have you seen similar artefacts with other waterfall software using the RTLSDR, or are they unique to this library (in which case it probably is a bug in my waterfall code)?

**Comment by jonschoning** [comment]
yes, it's the big block.  I believe it's unique to the library, as using the same rtl-sdr dongle with other programs capable of displaying waterfalls, such as gqrx (linux) or sdr# (windows), on the same laptop or a different computer, this phenomenon does not occur.  (I'm not sure what the underlying cause could be (i.e. gain, although the librtlsdr params for gain in this executable appear to be hardcoded) and if these programs compensate for that specifically).  I believe gqrx also uses librtlsdr (but it also has some libgnuradio libraries).

**Comment by adamwalker** [comment]
Sorry about the silence on this issue. 

I believe it is due to the automatic gain control on the dongle. I have updated the app so that the gain can be specified. I ran it, specifying the gain and stared at it for about 5 minutes and didn't see any artifacts. 

Unfortunately, setting the gain to the highest setting results in a smaller signal than if I dont specify it, which makes no sense to me. So, things are still a little odd.
